local LSM = LibStub("LibSharedMedia-3.0") 

-- Background
LSM:Register("background", "RenaitreFadeBorder", [[Interface\Addons\SharedMedia_Renaitre\background\RenaitreFadeBorder.tga]]) 
LSM:Register("background", "RenaitreFadeGloss", [[Interface\Addons\SharedMedia_Renaitre\background\RenaitreFadeGloss.tga]]) 
LSM:Register("background", "RenaitreFadeNormal", [[Interface\Addons\SharedMedia_Renaitre\background\RenaitreFadeNormal.tga]]) 
LSM:Register("background", "RenFlare", [[Interface\Addons\SharedMedia_Renaitre\background\RenFlare.tga]]) 
LSM:Register("background", "RenOrb", [[Interface\Addons\SharedMedia_Renaitre\background\RenOrb.tga]]) 
LSM:Register("background", "RenOrbSmall", [[Interface\Addons\SharedMedia_Renaitre\background\RenOrbSmall.tga]]) 
LSM:Register("background", "RageGuy", [[Interface\Addons\SharedMedia_Renaitre\background\RageGuy.tga]]) 
LSM:Register("background", "RageGuyFu", [[Interface\Addons\SharedMedia_Renaitre\background\RageGuyFu.tga]]) 

-- Border
LSM:Register("border", "RenaitreBeveled10", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreBeveled10.tga]]) 
LSM:Register("border", "RenaitreBeveled10x", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreBeveled10x.tga]]) 
LSM:Register("border", "RenaitreBeveled11", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreBeveled11.tga]]) 
LSM:Register("border", "RenaitreBeveled11x", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreBeveled11x.tga]]) 
LSM:Register("border", "RenaitreFade10", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade10.tga]]) 
LSM:Register("border", "RenaitreFade10blk", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade10blk.tga]]) 
LSM:Register("border", "RenaitreFade10x", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade10x.tga]]) 
LSM:Register("border", "RenaitreFade10xblk", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade10xblk.tga]]) 
LSM:Register("border", "RenaitreFade11", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade11.tga]]) 
LSM:Register("border", "RenaitreFade11blk", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade11blk.tga]]) 
LSM:Register("border", "RenaitreFade11x", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade11x.tga]]) 
LSM:Register("border", "RenaitreFade11xblk", [[Interface\Addons\SharedMedia_Renaitre\border\RenaitreFade11xblk.tga]]) 
LSM:Register("border", "RenDefine", [[Interface\Addons\SharedMedia_Renaitre\border\RenDefine.tga]]) 
LSM:Register("border", "RenFade", [[Interface\Addons\SharedMedia_Renaitre\border\RenFade.tga]]) 
LSM:Register("border", "RenFadeB", [[Interface\Addons\SharedMedia_Renaitre\border\RenFadeB.tga]]) 

-- Sound
LSM:Register("sound", "Camera Flash Charge", [[Interface\Addons\SharedMedia_Renaitre\sound\Camera Flash Charge.ogg]]) 
LSM:Register("sound", "Car Alarm", [[Interface\Addons\SharedMedia_Renaitre\sound\Car Alarm.ogg]]) 
LSM:Register("sound", "Clink", [[Interface\Addons\SharedMedia_Renaitre\sound\Clink.ogg]]) 
LSM:Register("sound", "Heart Beat 8", [[Interface\Addons\SharedMedia_Renaitre\sound\Heart Beat 8.ogg]]) 
LSM:Register("sound", "Hot AK47 Bolt Pull", [[Interface\Addons\SharedMedia_Renaitre\sound\Hot AK47 Bolt Pull.ogg]]) 
LSM:Register("sound", "Hot Airhorn", [[Interface\Addons\SharedMedia_Renaitre\sound\Hot Airhorn.ogg]]) 
LSM:Register("sound", "Hot Explosion", [[Interface\Addons\SharedMedia_Renaitre\sound\Hot Explosion.ogg]]) 
LSM:Register("sound", "Hot Its Me Bitches", [[Interface\Addons\SharedMedia_Renaitre\sound\Hot Its Me Bitches.ogg]]) 
LSM:Register("sound", "Hot Shotgun Reload", [[Interface\Addons\SharedMedia_Renaitre\sound\Hot Shotgun Reload.ogg]]) 
LSM:Register("sound", "Jigsaw Puppet Laugh", [[Interface\Addons\SharedMedia_Renaitre\sound\Jigsaw Puppet Laugh.ogg]]) 
LSM:Register("sound", "KanyeFinish", [[Interface\Addons\SharedMedia_Renaitre\sound\KanyeFinish.ogg]]) 
LSM:Register("sound", "OMNotInMyHouse", [[Interface\Addons\SharedMedia_Renaitre\sound\OMNotInMyHouse.ogg]]) 
LSM:Register("sound", "StereoDouchebag", [[Interface\Addons\SharedMedia_Renaitre\sound\StereoDouchebag.ogg]]) 
LSM:Register("sound", "StereoG_KICK", [[Interface\Addons\SharedMedia_Renaitre\sound\StereoG_KICK.ogg]]) 
LSM:Register("sound", "StereoStealth", [[Interface\Addons\SharedMedia_Renaitre\sound\StereoStealth.ogg]]) 
LSM:Register("sound", "StereoStun", [[Interface\Addons\SharedMedia_Renaitre\sound\StereoStun.ogg]]) 
LSM:Register("sound", "StereoVanish", [[Interface\Addons\SharedMedia_Renaitre\sound\StereoVanish.ogg]]) 
LSM:Register("sound", "SwordWhip", [[Interface\Addons\SharedMedia_Renaitre\sound\SwordWhip.ogg]]) 
LSM:Register("sound", "SwordWhipSlow", [[Interface\Addons\SharedMedia_Renaitre\sound\SwordWhipSlow.ogg]]) 
LSM:Register("sound", "Thunder", [[Interface\Addons\SharedMedia_Renaitre\sound\Thunder.ogg]]) 
LSM:Register("sound", "Thundercrack", [[Interface\Addons\SharedMedia_Renaitre\sound\Thundercrack.ogg]]) 

-- Statusbar
LSM:Register("statusbar", "rCurve1", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1.tga]]) 
LSM:Register("statusbar", "rCurve1h", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1h.tga]]) 
LSM:Register("statusbar", "rCurve1ho", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1ho.tga]]) 
LSM:Register("statusbar", "rCurve2", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve2.tga]]) 
LSM:Register("statusbar", "rCurve3", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3.tga]]) 
LSM:Register("statusbar", "rCurve3h", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3h.tga]]) 
LSM:Register("statusbar", "rCurve3ho", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3ho.tga]]) 
LSM:Register("statusbar", "rCurveG1", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1.tga]]) 
LSM:Register("statusbar", "rCurveG1h", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1h.tga]]) 
LSM:Register("statusbar", "rCurveG1ho", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve1ho.tga]]) 
LSM:Register("statusbar", "rCurveG2", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve2.tga]]) 
LSM:Register("statusbar", "rCurveG3", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3.tga]]) 
LSM:Register("statusbar", "rCurveG3h", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3h.tga]]) 
LSM:Register("statusbar", "rCurveG3ho", [[Interface\Addons\SharedMedia_Renaitre\statusbar\rCurve3ho.tga]]) 
LSM:Register("statusbar", "RenAscension", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenAscension.tga]]) 
LSM:Register("statusbar", "RenAscensionL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenAscensionL.tga]]) 
LSM:Register("statusbar", "RenCloak", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenCloak.tga]]) 
LSM:Register("statusbar", "RenCloakL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenCloakL.tga]]) 
LSM:Register("statusbar", "RenDeity", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenDeity.tga]]) 
LSM:Register("statusbar", "RenDeityL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenDeityL.tga]]) 
LSM:Register("statusbar", "RenDispatch", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenDispatch.tga]]) 
LSM:Register("statusbar", "RenFeint", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenFeint.tga]]) 
LSM:Register("statusbar", "RenFeint2", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenFeint2.tga]]) 
LSM:Register("statusbar", "RenFeintDark", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenFeintDark.tga]]) 
LSM:Register("statusbar", "RenFeint2Dark", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenFeint2Dark.tga]]) 
LSM:Register("statusbar", "RenFeintDouble", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenFeintDouble.tga]]) 
LSM:Register("statusbar", "RenHorizonDown", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenHorizonDown.tga]]) 
LSM:Register("statusbar", "RenHorizonUp", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenHorizonUp.tga]]) 
LSM:Register("statusbar", "RenaitreDefile", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDefile.tga]]) 
LSM:Register("statusbar", "RenaitreDefileL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDefileL.tga]]) 
LSM:Register("statusbar", "RenaitreDeity", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDeity.tga]]) 
LSM:Register("statusbar", "RenaitreDeityL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDeityL.tga]]) 
LSM:Register("statusbar", "RenaitreDeviant", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDeviant.tga]]) 
LSM:Register("statusbar", "RenaitreDeviantThin", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDeviantThin.tga]]) 
LSM:Register("statusbar", "RenaitreDeviantThinL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreDeviantThinL.tga]]) 
LSM:Register("statusbar", "RenaitreMinion", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreMinion.tga]]) 
LSM:Register("statusbar", "RenaitreMinionL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreMinionL.tga]]) 
LSM:Register("statusbar", "RenaitreSabrette", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreSabrette.tga]]) 
LSM:Register("statusbar", "RenaitreSabretteMedium", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreSabretteMedium.tga]]) 
LSM:Register("statusbar", "RenaitreSabretteWide", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreSabretteWide.tga]]) 
LSM:Register("statusbar", "RenaitreTunnel", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreTunnel.tga]]) 
LSM:Register("statusbar", "RenaitreTunnelL", [[Interface\Addons\SharedMedia_Renaitre\statusbar\RenaitreTunnelL.tga]]) 

-- Glow
LSM:Register("glow", "RenaitreDeityGlow", [[Interface\Addons\SharedMedia_Renaitre\glow\RenaitreDeityGlow.tga]]) 
LSM:Register("glow", "RenaitreSabretteGlow", [[Interface\Addons\SharedMedia_Renaitre\glow\RenaitreSabretteGlow.tga]]) 
